### ISSUE TITLE
Introduction of error codes

### ISSUE THREAD

**Issue by mormod** [Benzammour/yobemag#3]
Currently, functions that return error codes have a return value of `uint8_t`. Depending on the function, that could imply different things, for example the number of read bytes in `rom_load`. To avoid that confusion, I suggest using something like this:
```
typedef enum error_code {
    ERR_OK,
    ERR_FAIL,
    ERR_TO,
    ...
} error_code;
```
This would make interpretation of return values much easier.

TODO for places that need error codes:

- [x] `rom_load`
- [x] `mem_init`
- [x] `rom_setup` (maybe just remove return 0? and make void instead)
- [x] `lcd_load` (same as `rom_setup`)

**Comment by marcluque** [comment]
Note the edit of a todo list for places that need review
