### ISSUE TITLE
Start using proper documentation software

### ISSUE THREAD

**Issue by marcluque** [Benzammour/yobemag#6]
I suggest a documentation pipeline that works with the following tools via Github Actions:
- doxygen
- sphinx (RTD theme)
- breathe plugin

It could publish auto-generated documentation to a github-pages site.

**Comment by mormod** [comment]
![image](https://user-images.githubusercontent.com/20692341/195957567-ff0564e4-9d43-4186-9b18-0eae4911b920.png)

**Comment by mormod** [comment]
SGTM
