### ISSUE TITLE
Add clang-format & clang-tidy

### ISSUE THREAD

**Issue by marcluque** [Benzammour/yobemag#9]
Adding the two tools should help enforcing coding convention consistency.

**Comment by mormod** [comment]
How about adding pre-merge hooks which check, if a file is formatted correctly? If it is not, the merge request could be postponed until the relevant fixes to the layout are made

**Comment by marcluque** [comment]
Absolutely. I think that both toola have linting capabilities.

**Comment by mormod** [comment]
Are the tools from cretro ready to deploy here?

**Comment by marcluque** [comment]
I think there are some final settings that need to be discussed, like asterisk alignment or specific clang-tidy checks. Also a bit more testing of the tools would be good to then finally put them in a pre-commit hook 🤔

**Comment by marcluque** [comment]
Yes, exactly
